+  Bugfixes:
@@ -1,13 +1,26 @@
 uadns (0.8) BETA; urgency=low

+  Bugfixes:
   * Spurious `server failure on unidentifiable query' warning suppressed.
-  * install-sh (from autoconf 2.12 Debian r13) included.
   * adnslogres: cast chars to unsigned char before using ctype.h macros.
+  * In _beforeselect, global failure now means zero timeout, and in
+    tcp_events, really never try to do anything with the TCP connection if
+    act is zero.  This might possibly cause an infinite delay (ie, lockup)
+    if things go badly wrong *and* a really unlikely race happens.
+  * Test suite `lines of syscall left' value is correct; !0 is failure.
+
+  Portability fixes:
+  * install-sh (from autoconf 2.12 Debian r13) included.
+
+  Documentation improvements:
   * Security/performance note added, about local nameservers and DNSSEC.
   * Documented that adns_rr_info _rr_hostaddr ( ) for address list
     means permanent failure, and ? means temporary failure.
   * Typo (*now for now in _beforeselect description) in adns.h fixed.
-  * In _beforeselect, global system failure now produces zero timeout.
+
+  Changes to produce more defensive code:
+  * In adns_wait, assert that the timeout is not infinite.
+  * Make qu->id start out as -2 when initially allocated.

  --

diff --git a/regress/r1test b/regress/r1test
--- a/regress/r1test
+++ b/regress/r1test
@@ -42,13 +42,20 @@ do
 	then
 		:
 	else
-		failed=true
+		failwhy="$failwhy WRONG OUTPUT"
 	fi
 done
 
-if $failed
+cat >"$ocase.leftover"
+if egrep . /dev/null "$ocase.leftover"
 then
-	echo >&2 "FAILED $case - WRONG OUTPUT - lines of syscall remaining `wc -l`"
+	failwhy="$failwhy EXITED EARLY"
+fi
+
+if [ "x$failwhy" != x ]
+then
+	scremain="`wc -l <\"$ocase.leftover\"`"
+	echo >&2 "FAILED $case -$failwhy - lines of syscall remaining $scremain"
 	mrc=2
 	exit
 fi
